### ISSUE TITLE
No editor found for version "xxx"

### ISSUE THREAD

**Issue by xucian** [kuler90/setup-unity#9]
Hi,

Getting this error on a self-hosted windows machine.
The Unity was installed from a previous step by the same action (I think it also failed eventually, but I didn't care at that point).
Any ideas?

2022-06-28T15:08:33.2208675Z with:
2022-06-28T15:08:33.2209778Z   unity-modules: windows-il2cpp
visualstudio

2022-06-28T15:08:33.2210718Z   unity-modules-child: true
2022-06-28T15:08:33.2211725Z   project-path: ***
2022-06-28T15:08:33.2212868Z env:
2022-06-28T15:08:33.2213598Z   PLATFORM: StandaloneWindows64
2022-06-28T15:08:33.2214397Z   DBD_RELEASE_PHASE: dev
2022-06-28T15:08:33.2215182Z   DBD_BUILD_TYPE: DBD_DEV
2022-06-28T15:08:33.2215911Z ##[endgroup]
2022-06-28T15:08:33.4412232Z [command]"C:/Program Files/Unity Hub/Unity Hub.exe" -- --headless editors --installed
2022-06-28T15:08:33.4738398Z 
2022-06-28T15:08:39.8489414Z 2021.3.5f1 , installed at C:\Program Files\Unity\Hub\Editor\2021.3.5f1\Editor\Unity.exe
2022-06-28T15:08:39.8493908Z 2020.3.18f1 , installed at C:\Program Files\Unity\Hub\Editor\2020.3.18f1\Editor\Unity.exe
2022-06-28T15:08:39.8495305Z 2021.3.4f1 , installed at C:\Program Files\Unity\Hub\Editor\2021.3.4f1\Editor\Unity.exe
2022-06-28T15:08:41.4555995Z 
2022-06-28T15:08:41.4568061Z [command]"C:/Program Files/Unity Hub/Unity Hub.exe" -- --headless install-modules --version 2021.3.5f1 --module windows-il2cpp --childModules
2022-06-28T15:08:41.4979719Z 
2022-06-28T15:08:49.3163387Z Failed to execute the command due the following, please see '-- --headless help' for assistance.
2022-06-28T15:08:49.3164758Z Error: No editor found for version "2021.3.5f1".
2022-06-28T15:08:50.7966425Z 
2022-06-28T15:08:50.8013331Z ##[error]unity modules installation failed
2022-06-28T15:08:50.9089278Z ##[group]Run echo "Dumping current debug info to __build-win--fails-<run-id>"
2022-06-28T15:08:50.9090603Z [36;1mecho "Dumping current debug info to __build-win--fails-<run-id>"[0m
2022-06-28T15:08:50.9092006Z [36;1m$projectPath="***"[0m
2022-06-28T15:08:50.9093296Z [36;1m$runnerTempPath="$projectPath/../../_temp"[0m
2022-06-28T15:08:50.9095044Z [36;1mCopy-Item "$runnerTempPath" -Destination "$runnerTempPath/../__build-win--fails-2577213692" -Recurse[0m
2022-06-28T15:08:50.9148388Z shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"

**Comment by tfgstudios** [comment]
Hey. Thanks for reply!

Yes, and the same error appears. I've updated the hub to the latest version
and now it says il2cpp module is already installed, and it still fails. I
noticed the hub wasn't signed in, so I did it manually, just to hopefully
come closer to a solution, but I still get an error:

Omitting module windows-il2cpp because it's already installed
Failed to execute the command due the following, please see '-- --headless
help' for assistance.
Error: No modules found to install.
"C:/Program Files/Unity Hub/Unity Hub.exe" -- --headless install-modules
--version 2021.3.5f1 --module visualstudio --childModules

Then it proceeds installing visual studio (it takes a few minutes) and then
it fails. It seems this is a secondary issue where the setup should've
ended earlier, the moment the error appearred.

**Comment by kuler90** [comment]
Sorry, I've just run [tests](https://github.com/kuler90/setup-unity/actions/runs/2581830219) and it's passed on GitHub-hosted Windows. Maybe you have some problems with Unity path settings. Try to execute Unity Hub with '-- --headless help' and check the Unity installation path.

**Comment by tfgstudios** [comment]
> Sorry, I've just run [tests](https://github.com/kuler90/setup-unity/actions/runs/2581830219) and it's passed on GitHub-hosted Windows. Maybe you have some problems with Unity path settings. Try to execute Unity Hub with '-- --headless help' and check the Unity installation path.

Hm, I see. Could you run a test just for 2021.3.5f1? I see 2021.3 isn't on the tests list. Maybe there's some problem Unity introduced, although I think this is less probable.

Listing the installed editors via hub CLI gives me:
2020.3.18f1 , installed at C:\Program Files\Unity\Hub\Editor\2020.3.18f1\Editor\Unity.exe
2021.3.4f1 , installed at C:\Program Files\Unity\Hub\Editor\2021.3.4f1\Editor\Unity.exe
2021.3.5f1 , installed at C:\Program Files\Unity\Hub\Editor\2021.3.5f1\Editor\Unity.exe

**Comment by tfgstudios** [comment]
any updates on this?
running `"C:/Program Files/Unity Hub/Unity Hub.exe" -- --headless install-modules --version 2021.3.8f1 --module windows-il2cpp --module visualstudio --childModules` gives:

[2021.3.8f1 - Microsoft Visual Studio Community 2019] failed to install. Error given: Installation Failed                                                                                                                                                                                                                           [2021.3.8f1 - Windows Build Support (IL2CPP)] installing...                                                                                                                                                                                                                                                                         Completed with errors.                                                                                                                                                                                                                                                                                                              ERROR: Licensing SDK logging callback is not registered. Please use 'registerLoggingAdapter' function from the SDK to do so.                                                                                                                                                                                                        This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:                                                                                                                                    Error: write EPIPE                                                                                                                                                                                                                                                                                                                      at afterWriteDispatched (internal/stream_base_commons.js:156:25)                                                                                                                                                                                                                                                                    at writeGeneric (internal/stream_base_commons.js:147:3)                                                                                                                                                                                                                                                                             at Socket._writeGeneric (net.js:785:11)                                                                                                                                                                                                                                                                                             at Socket._write (net.js:797:8)                                                                                                                                                                                                                                                                                                     at writeOrBuffer (internal/streams/writable.js:358:12)                                                                                                                                                                                                                                                                              at Socket.Writable.write (internal/streams/writable.js:303:10)                                                                                                                                                                                                                                                                      at Server.emit (C:\Program Files\Unity Hub\resources\app.asar\node_modules\node-ipc\dao\socketServer.js:97:12)                                                                                                                                                                                                                      at C:\Program Files\Unity Hub\resources\app.asar\build\main\common\ipc\UnityIPCServer.js:41:29                                                                                                                                                                                                                                      at Array.forEach (<anonymous>)                                                                                                                                                                                                                                                                                                      at UnityIPCServer.emitAll (C:\Program Files\Unity Hub\resources\app.asar\build\main\common\ipc\UnityIPCServer.js:40:33)                                                                                                                                                                                                         This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:                                                                                                                                    Error: write EPIPE                                                                                                                                                                                                                                                                                                                      at afterWriteDispatched (internal/stream_base_commons.js:156:25)                                                                                                                                                                                                                                                                    at writeGeneric (internal/stream_base_commons.js:147:3)                                                                                                                                                                                                                                                                             at Socket._writeGeneric (net.js:785:11)                                                                                                                                                                                                                                                                                             at Socket._write (net.js:797:8)                                                                                                                                                                                                                                                                                                     at writeOrBuffer (internal/streams/writable.js:358:12)                                                                                                                                                                                                                                                                              at Socket.Writable.write (internal/streams/writable.js:303:10)                                                                                                                                                                                                                                                                      at Server.emit (C:\Program Files\Unity Hub\resources\app.asar\node_modules\node-ipc\dao\socketServer.js:97:12)                                                                                                                                                                                                                      at C:\Program Files\Unity Hub\resources\app.asar\build\main\common\ipc\UnityIPCServer.js:41:29                                                                                                                                                                                                                                      at Array.forEach (<anonymous>)                                                                                                                                                                                                                                                                                                      at UnityIPCServer.emitAll (C:\Program Files\Unity Hub\resources\app.asar\build\main\common\ipc\UnityIPCServer.js:40:33)
